-   id: check-package-depends
    name: check package depends
    description: check for missing dependencies in package.xml
    language: python
    entry: check-package-depends
    files: package.xml
