name: autoware-guideline-check
description: ""

inputs:
  workspace:
    description: "Workspace directory"
    required: false
    type: string

runs:
  using: docker
  image: Dockerfile
  args:
    - "autoware-guideline-check"
    - "--workspace ${{ inputs.workspace }}"
